import Link from 'next/link'
import { UrlInput } from '@/components/UrlInput'
import { PricingCards } from '@/components/PricingCards'

const useCases = ['Summarize a 400-comment travel thread', 'Extract the best PC build advice', 'Find the consensus in a skincare routine debate', 'Turn personal finance advice into an action plan']
const faqs = [
  ['Does it work without the Reddit API?', 'Yes. The MVP uses Reddit JSON as the default ingestion path and includes mock demo mode when API keys are missing.'],
  ['Does it copy Reddit comments?', 'No. It paraphrases useful comments and only shows short summaries with score data when available.'],
  ['What makes it different from a generic chatbot?', 'ThreadGuide ranks comments, detects repeated advice and disagreements, then renders structured JSON into decision-focused sections.'],
  ['Can I save guides?', 'Yes for logged-in users, with Pro positioned for saved guide history and higher limits.']
]

export default function Home() {
  return <main><nav className="mx-auto flex max-w-6xl items-center justify-between px-5 py-5"><Link href="/" className="text-xl font-black tracking-tight">ThreadGuide</Link><div className="flex items-center gap-4 text-sm font-medium"><Link href="/pricing">Pricing</Link><Link href="/login" className="rounded-full bg-ink px-4 py-2 text-white">Login</Link></div></nav><section className="mx-auto max-w-6xl px-5 py-16 text-center md:py-24"><div className="mx-auto max-w-3xl"><p className="mb-4 inline-flex rounded-full border border-line bg-white px-4 py-2 text-sm font-semibold text-muted shadow-sm">ChatGPT specifically for Reddit threads</p><h1 className="text-4xl font-black tracking-tight md:text-6xl">Turn any Reddit thread into a step-by-step guide.</h1><p className="mt-6 text-lg leading-8 text-slate-600">Paste a Reddit URL and get consensus, recommendations, pros, cons, best comments, FAQ, contradictions, and a practical action plan.</p><div className="mt-8"><UrlInput /></div></div></section><section className="mx-auto grid max-w-6xl gap-4 px-5 md:grid-cols-4">{useCases.map((item) => <div key={item} className="rounded-2xl border border-line bg-white p-5 shadow-sm"><p className="font-semibold">{item}</p></div>)}</section><section className="mx-auto grid max-w-6xl gap-8 px-5 py-20 md:grid-cols-2"><div className="rounded-3xl border border-line bg-white p-6 shadow-soft"><p className="text-sm font-bold uppercase text-muted">Before</p><p className="mt-4 text-slate-600">A 400-comment thread with repeated advice, jokes, buried expert comments, disagreements, and no clear next step.</p></div><div className="rounded-3xl border border-line bg-white p-6 shadow-soft"><p className="text-sm font-bold uppercase text-brand">After</p><p className="mt-4 text-slate-600">A polished guide with consensus, risks, top recommendations, FAQ, and a step-by-step plan tailored to the subreddit.</p></div></section><section className="mx-auto max-w-5xl px-5 pb-20"><h2 className="mb-6 text-center text-3xl font-black">Simple pricing</h2><PricingCards /></section><section className="mx-auto max-w-4xl px-5 pb-20"><h2 className="mb-6 text-3xl font-black">FAQ</h2><div className="divide-y divide-line rounded-3xl border border-line bg-white p-6 shadow-soft">{faqs.map(([q, a]) => <div key={q} className="py-4 first:pt-0 last:pb-0"><p className="font-semibold">{q}</p><p className="mt-1 text-sm leading-6 text-slate-600">{a}</p></div>)}</div></section><footer className="border-t border-line bg-white px-5 py-8 text-center text-sm text-muted"><Link href="/privacy">Privacy</Link><span className="mx-3">•</span><Link href="/terms">Terms</Link></footer></main>
}
